apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: suilens-2306259963
type: Opaque
stringData:
  catalog-db-url: postgres://catalog:catalog@10.43.222.79:5432/catalog
  order-db-url: postgres://orders:orders@10.43.6.18:5432/orders
  notification-db-url: postgres://notifications:notifications@10.43.216.186:5432/notifications
  rabbitmq-url: amqp://guest:guest@10.43.46.106:5672
